// File generated by FlutterFire CLI & configured with project credentials.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
      default:
        return android;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyAlNZlpa8eaFQq0mO69RpOjCA66Q22Z8',
    appId: '1:546125933045:web:1fde7abd8bd26ea9a558bc',
    messagingSenderId: '546125933045',
    projectId: 'nara-524a9',
    authDomain: 'nara-524a9.firebaseapp.com',
    storageBucket: 'nara-524a9.firebasestorage.app',
    measurementId: 'G-8ND3Y6JENX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxl5CSNkFqminP2PGAc1j6lllVwMmdTxE',
    appId: '1:546125933045:android:c7cb7955a341384da558bc',
    messagingSenderId: '546125933045',
    projectId: 'nara-524a9',
    storageBucket: 'nara-524a9.firebasestorage.app',
  );
}
